before_script:
  - export DISPLAY=:99.0
cache:
  directories:
    - node_modules
install:
  - npm install
language: node_js
matrix:
  fast_finish: true
node_js:
  - 'lts/*'
os:
  - linux
  - osx
  - windows
script:
  - npm run build
